name: Code style

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  dart_format:
    name: Dart format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ vars.FLUTTER_VERSION }}
    - run: flutter pub get
    - run: dart format --set-exit-if-changed lib
